### ISSUE TITLE
9월 10일 강의 코드 참고용으로 필요할 것 같아 이슈 남깁니다.

### ISSUE THREAD

**Issue by roamgom** [kaggler-tv/dku-kaggle-class#7]
이번 강의 Jupyter 예제 코드 Logistic Regression ROC curve를 그리는 부분에서

`from kaggler.metrics import plot_roc_curve, plot_pr_curve` 부분에서 에러가 발생할 수 있습니다.

두가지 해결방법이 있는데 하나는 이정윤 교수님께서 만드신 `Kaggler` 패키지를 설치하는 방법과
plot을 그리기 전 아래 코드를 붙여 실행하시면 됩니다.

참고하시길 바랍니다.

Kaggler 패키지 설치
[깃헙 링크](https://github.com/jeongyoonlee/Kaggler)
```shell
pip3 install Kaggler
```

코드를 추가하여 사용할 경우,
아래 코드를 추가해주세요. [참고](https://github.com/jeongyoonlee/Kaggler/blob/master/kaggler/metrics/classification.py)

**추가용 코드**
```python
# from kaggler.metrics import plot_roc_curve, plot_pr_curve
from sklearn.metrics import roc_curve, precision_recall_curve

def plot_roc_curve(y, p):
    fpr, tpr, _ = roc_curve(y, p)

    plt.plot(fpr, tpr)
    plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')


def plot_pr_curve(y, p):
    precision, recall, _ = precision_recall_curve(y, p)

    plt.step(recall, precision, color='b', alpha=0.2, where='post')
    plt.fill_between(recall, precision, step='post', alpha=0.2, color='b')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.ylim([0.0, 1.05])
    plt.xlim([0.0, 1.0])
```

**plot 실행**
```python
plt.figure(figsize=(16, 16))
plt.subplot(1, 2, 1)
plot_roc_curve(y, p);
plt.title('AUC Curve')
plt.subplot(1, 2, 2)
plot_pr_curve(y, p);
plt.title('Precision-Recall Curve')
```

실행결과

<img width="1369" alt="스크린샷 2020-09-10 오후 7 42 05" src="https://user-images.githubusercontent.com/24652225/92719150-b62c6800-f39d-11ea-9c6c-c5f121fb1db2.png">

**추가로 질문 사항은 댓글로 남겨주시면 감사하겠습니다** 😁

**Comment by rch1025** [comment]
p{margin-top:0;margin-bottom:0}
    


    감사합니다, 박사님 !
코로나 조심하시고 한 학기동안 고생많으셨습니다.

- 노승찬 올림 -

--------- 원본 메일 ---------

    
        보낸사람: Jeong-Yoon Lee <notifications@github.com>
        받는사람: kaggler-tv/dku-kaggle-class <dku-kaggle-class@noreply.github.com>
        
            참조: rch1025 <chanee2525@daum.net>, Comment <comment@noreply.github.com>
        
        날짜: 20.12.19 04:48 GMT +0900
        제목: Re: [kaggler-tv/dku-kaggle-class] 9월 10일 강의 코드 참고용으로 필요할 것 같아 이슈 남깁니다. (#7)
        
        
    
    
        
Closed #7.
